version_list:
  # - 'nocuda_py36_torch1.5.0'
  # - 'nocuda_py37_torch1.5.0'
  # - 'nocuda_py38_torch1.5.0'
  # - 'nocuda_py36_torch1.6.0'
  # - 'nocuda_py37_torch1.6.0'
  # - 'nocuda_py38_torch1.6.0'
  # - 'nocuda_py36_torch1.7.0'
  # - 'nocuda_py37_torch1.7.0'
  # - 'nocuda_py38_torch1.7.0'
  # - 'nocuda_py36_torch1.8.0'
  - 'nocuda_py37_torch1.8.0'
  - 'nocuda_py38_torch1.8.0'
  - 'nocuda_py39_torch1.8.0'
  # - 'nocuda_py36_torch1.9.0'
  - 'nocuda_py37_torch1.9.0'
  - 'nocuda_py38_torch1.9.0'
  - 'nocuda_py39_torch1.9.0'
  # - 'nocuda_py36_torch1.10.0'
  - 'nocuda_py37_torch1.10.0'
  - 'nocuda_py38_torch1.10.0'
  - 'nocuda_py39_torch1.10.0'
  - 'nocuda_py37_torch1.11.0'
  - 'nocuda_py38_torch1.11.0'
  - 'nocuda_py39_torch1.11.0'
  - 'nocuda_py310_torch1.11.0'
  - 'nocuda_py37_torch1.12.0'
  - 'nocuda_py38_torch1.12.0'
  - 'nocuda_py39_torch1.12.0'
  - 'nocuda_py310_torch1.12.0'
  - 'nocuda_py37_torch1.13.0'
  - 'nocuda_py38_torch1.13.0'
  - 'nocuda_py39_torch1.13.0'
  - 'nocuda_py310_torch1.13.0'
  - 'nocuda_py38_torch2.0.0'
  - 'nocuda_py39_torch2.0.0'
  - 'nocuda_py310_torch2.0.0'
  - 'nocuda_py311_torch2.0.0'
  # - 'cuda101_py36_torch1.5.0'
  # - 'cuda101_py37_torch1.5.0'
  # - 'cuda101_py38_torch1.5.0'
  # - 'cuda102_py36_torch1.5.0'
  # - 'cuda102_py37_torch1.5.0'
  # - 'cuda102_py38_torch1.5.0'
  # - 'cuda101_py36_torch1.6.0'
  # - 'cuda101_py37_torch1.6.0'
  # - 'cuda101_py38_torch1.6.0'
  # - 'cuda102_py36_torch1.6.0'
  # - 'cuda102_py37_torch1.6.0'
  # - 'cuda102_py38_torch1.6.0'
  # - 'cuda101_py36_torch1.7.0'
  # - 'cuda101_py37_torch1.7.0'
  # - 'cuda101_py38_torch1.7.0'
  # - 'cuda102_py36_torch1.7.0'
  # - 'cuda102_py37_torch1.7.0'
  # - 'cuda102_py38_torch1.7.0'
  # - 'cuda101_py36_torch1.8.0'
  - 'cuda101_py37_torch1.8.0'
  - 'cuda101_py38_torch1.8.0'
  - 'cuda101_py39_torch1.8.0'
  # - 'cuda102_py36_torch1.8.0'
  - 'cuda102_py37_torch1.8.0'
  - 'cuda102_py38_torch1.8.0'
  - 'cuda102_py39_torch1.8.0'
  # - 'cuda111_py36_torch1.8.0'
  - 'cuda111_py37_torch1.8.0'
  - 'cuda111_py38_torch1.8.0'
  - 'cuda111_py39_torch1.8.0'
  # - 'cuda102_py36_torch1.9.0'
  - 'cuda102_py37_torch1.9.0'
  - 'cuda102_py38_torch1.9.0'
  - 'cuda102_py39_torch1.9.0'
  # - cuda111_py36_torch1.9.0'
  - 'cuda111_py37_torch1.9.0'
  - 'cuda111_py38_torch1.9.0'
  - 'cuda111_py39_torch1.9.0'
  # - 'cuda102_py36_torch1.10.0'
  - 'cuda102_py37_torch1.10.0'
  - 'cuda102_py38_torch1.10.0'
  - 'cuda102_py39_torch1.10.0'
  # - 'cuda111_py36_torch1.10.0'
  - 'cuda111_py37_torch1.10.0'
  - 'cuda111_py38_torch1.10.0'
  - 'cuda111_py39_torch1.10.0'
  # - 'cuda113_py36_torch1.10.0'
  - 'cuda113_py37_torch1.10.0'
  - 'cuda113_py38_torch1.10.0'
  - 'cuda113_py39_torch1.10.0'
  - 'cuda113_py37_torch1.11.0'
  - 'cuda113_py38_torch1.11.0'
  - 'cuda113_py39_torch1.11.0'
  - 'cuda113_py310_torch1.11.0'
  - 'cuda115_py37_torch1.11.0'
  - 'cuda115_py38_torch1.11.0'
  - 'cuda115_py39_torch1.11.0'
  - 'cuda115_py310_torch1.11.0'
  - 'cuda113_py37_torch1.12.0'
  - 'cuda113_py38_torch1.12.0'
  - 'cuda113_py39_torch1.12.0'
  - 'cuda113_py310_torch1.12.0'
  - 'cuda116_py37_torch1.12.0'
  - 'cuda116_py38_torch1.12.0'
  - 'cuda116_py39_torch1.12.0'
  - 'cuda116_py310_torch1.12.0'
  - 'cuda116_py37_torch1.13.0'
  - 'cuda116_py38_torch1.13.0'
  - 'cuda116_py39_torch1.13.0'
  - 'cuda116_py310_torch1.13.0'
  - 'cuda117_py37_torch1.13.0'
  - 'cuda117_py38_torch1.13.0'
  - 'cuda117_py39_torch1.13.0'
  - 'cuda117_py310_torch1.13.0'
  - 'cuda117_py38_torch2.0.0'
  - 'cuda117_py39_torch2.0.0'
  - 'cuda117_py310_torch2.0.0'
  - 'cuda117_py311_torch2.0.0'
  - 'cuda118_py38_torch2.0.0'
  - 'cuda118_py39_torch2.0.0'
  - 'cuda118_py310_torch2.0.0'
  - 'cuda118_py311_torch2.0.0'
download_path: "/home/PJLAB/lijialun/Downloads/pytorch/artifects"
version: v2.0.0